[2024-07-03T12:22:42.466+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_send_emails scheduled__2024-07-02T07:10:00+00:00 [queued]>
[2024-07-03T12:22:42.483+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_send_emails scheduled__2024-07-02T07:10:00+00:00 [queued]>
[2024-07-03T12:22:42.489+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T12:22:42.592+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_send_emails> on 2024-07-02 07:10:00+00:00
[2024-07-03T12:22:42.597+0000] {standard_task_runner.py:57} INFO - Started process 24187 to run task
[2024-07-03T12:22:42.605+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_send_emails', 'scheduled__2024-07-02T07:10:00+00:00', '--job-id', '1069', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpm7iwbtek']
[2024-07-03T12:22:42.607+0000] {standard_task_runner.py:85} INFO - Job 1069: Subtask id_task_send_emails
[2024-07-03T12:22:42.679+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_send_emails scheduled__2024-07-02T07:10:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T12:22:42.777+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_send_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T07:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T07:10:00+00:00'
[2024-07-03T12:22:42.778+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T12:22:42.778+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:22:42.778824_User@StatDep: EmailRobot in screated.
[2024-07-03T12:22:42.779+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:22:42.779026_User@StatDep: send_validation_results is started...
[2024-07-03T12:22:42.792+0000] {logging_mixin.py:151} INFO -    #>2024-07-03 12:22:42.792072_conneciton to db is set.
[2024-07-03T12:22:42.794+0000] {logging_mixin.py:151} INFO -    #>2024-07-03 12:22:42.794040_cursor execution is successful.
[2024-07-03T12:22:42.794+0000] {logging_mixin.py:151} INFO -    extracted information for about report sumbissions found...
[2024-07-03T12:22:42.796+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:22:42.796369_User@StatDep: email object ready to be sent:
[2024-07-03T12:22:43.193+0000] {logging_mixin.py:151} WARNING - send: 'ehlo [172.20.0.6]\r\n'
[2024-07-03T12:22:43.257+0000] {logging_mixin.py:151} WARNING - reply: b'250-smtp29.i.mail.ru\r\n'
[2024-07-03T12:22:43.258+0000] {logging_mixin.py:151} WARNING - reply: b'250-SIZE 73400320\r\n'
[2024-07-03T12:22:43.259+0000] {logging_mixin.py:151} WARNING - reply: b'250-8BITMIME\r\n'
[2024-07-03T12:22:43.260+0000] {logging_mixin.py:151} WARNING - reply: b'250-PIPELINING\r\n'
[2024-07-03T12:22:43.261+0000] {logging_mixin.py:151} WARNING - reply: b'250-DSN\r\n'
[2024-07-03T12:22:43.262+0000] {logging_mixin.py:151} WARNING - reply: b'250-SMTPUTF8\r\n'
[2024-07-03T12:22:43.263+0000] {logging_mixin.py:151} WARNING - reply: b'250 AUTH PLAIN LOGIN XOAUTH2\r\n'
[2024-07-03T12:22:43.264+0000] {logging_mixin.py:151} WARNING - reply: retcode (250); Msg: b'smtp29.i.mail.ru\nSIZE 73400320\n8BITMIME\nPIPELINING\nDSN\nSMTPUTF8\nAUTH PLAIN LOGIN XOAUTH2'
[2024-07-03T12:22:43.266+0000] {logging_mixin.py:151} WARNING - send: 'AUTH PLAIN AGtoYWxpbXpvZEBsaXN0LnJ1AEdSWFFSakMyYms0cVpIQjI2VXFk\r\n'
[2024-07-03T12:22:43.517+0000] {logging_mixin.py:151} WARNING - reply: b'235 Authentication succeeded\r\n'
[2024-07-03T12:22:43.518+0000] {logging_mixin.py:151} WARNING - reply: retcode (235); Msg: b'Authentication succeeded'
[2024-07-03T12:22:43.520+0000] {logging_mixin.py:151} WARNING - send: 'mail FROM:<khalimzod@list.ru> size=1366\r\n'
[2024-07-03T12:22:43.581+0000] {logging_mixin.py:151} WARNING - reply: b'250 OK\r\n'
[2024-07-03T12:22:43.582+0000] {logging_mixin.py:151} WARNING - reply: retcode (250); Msg: b'OK'
[2024-07-03T12:22:43.583+0000] {logging_mixin.py:151} WARNING - send: 'rcpt TO:<ihalimzod@nbt.tj>\r\n'
[2024-07-03T12:22:43.649+0000] {logging_mixin.py:151} WARNING - reply: b'250 Accepted\r\n'
[2024-07-03T12:22:43.650+0000] {logging_mixin.py:151} WARNING - reply: retcode (250); Msg: b'Accepted'
[2024-07-03T12:22:43.650+0000] {logging_mixin.py:151} WARNING - send: 'data\r\n'
[2024-07-03T12:22:43.728+0000] {logging_mixin.py:151} WARNING - reply: b'354 Enter message, ending with "." on a line by itself\r\n'
[2024-07-03T12:22:43.728+0000] {logging_mixin.py:151} WARNING - reply: retcode (354); Msg: b'Enter message, ending with "." on a line by itself'
[2024-07-03T12:22:43.729+0000] {logging_mixin.py:151} WARNING - data: (354, b'Enter message, ending with "." on a line by itself')
[2024-07-03T12:22:43.730+0000] {logging_mixin.py:151} WARNING - send: b'Content-Type: multipart/mixed; boundary="===============0576331780815829641=="\r\nMIME-Version: 1.0\r\nSubject: =?utf-8?b?b21vckBuYnQudGo6INGE0LDQudC7IEhLLnYwLjAwMDAuMzEwMTIwMjQueGxzeCDQt9Cw0LPRgNGD0LbQtdC90L3Ri9C1INCyUDIgMjAyNC0wNy0wMyAxNTozMzo1MiswMDowMCDQndCVINCf0KDQmNCd0K/Qog==?=\r\nFrom: khalimzod@list.ru\r\nTo: =?utf-8?b?0KXQsNC70LjQvNC30L7QtCDQmNGB0LzQvtC40Lsg0JDQsdC00YPRgNCw0YXQvNC+0L0gPGloYWxpbXpvZEBuYnQudGo+?=\r\n\r\n--===============0576331780815829641==\r\nContent-Type: text/plain; charset="utf-8"\r\nMIME-Version: 1.0\r\nContent-Transfer-Encoding: base64\r\n\r\n0JfQtNGA0LDQstGB0YLQstGD0LnRgtC1LCAKINCaINGB0L7QttCw0LvQtdC90LjRjiDRhNCw0LnQ\r\nuyDRgSDQuNC80LXQvdC10LwgSEsudjAuMDAwMC4zMTAxMjAyNC54bHN4LCDQt9Cw0LPRgNGD0LbQ\r\ntdC90L3Ri9C5INCyIDIwMjQtMDctMDMgMTU6MzM6NTIrMDA6MDAg0L3QtSDQsdGL0Lsg0L/RgNC4\r\n0L3Rj9GC0YHQuNGB0YLQtdC80L7QuSDQsNCy0YLQvtC80LDRgtC40YfQtdGB0LrQvtC5INC+0LHR\r\ngNCw0LHQvtGC0LrQuC4g0J/QvtC20LDQu9GD0LnRgdGC0LAsINC/0YDQvtCy0LXRgNGM0YLQtSDQ\r\nt9Cw0L/QvtC70L3QtdC90LjQtSDRhNCw0LnQu9CwLiAKINCU0L7Qv9C+0LvQvdC40YLQtdC70YzQ\r\nvdGL0LUg0YHQstC10LTQtdC90YzRjyDQv9C+INC+0LHQvdCw0YDRg9C20LXQvdC90YvQvCDQvtGI\r\n0LjQsdC60LDQvCDQv9GA0LjQu9C+0LbQtdC90L3RiyDQuiDQv9C40YHRjNC80YMuCiBDINGD0LLQ\r\nsNC20LXQvdC40LXQvCwgCiDQlNC10L/QsNGA0YLQsNC80LXQvdGCINGB0YLQsNGC0LjRgdGC0LjQ\r\nutC4INC4INC/0LvQsNGC0LXQttC90L7Qs9C+INCx0LDQu9Cw0L3RgdCwLiA=\r\n\r\n--===============0576331780815829641==--\r\n.\r\n'
[2024-07-03T12:22:43.869+0000] {logging_mixin.py:151} WARNING - reply: b'550 your mailer sends invalid headers\r\n'
[2024-07-03T12:22:43.870+0000] {logging_mixin.py:151} WARNING - reply: retcode (550); Msg: b'your mailer sends invalid headers'
[2024-07-03T12:22:43.870+0000] {logging_mixin.py:151} WARNING - data: (550, b'your mailer sends invalid headers')
[2024-07-03T12:22:43.871+0000] {logging_mixin.py:151} WARNING - send: 'rset\r\n'
[2024-07-03T12:22:43.934+0000] {logging_mixin.py:151} WARNING - reply: b'250 Reset OK\r\n'
[2024-07-03T12:22:43.935+0000] {logging_mixin.py:151} WARNING - reply: retcode (250); Msg: b'Reset OK'
[2024-07-03T12:22:43.936+0000] {logging_mixin.py:151} WARNING - send: 'QUIT\r\n'
[2024-07-03T12:22:44.200+0000] {logging_mixin.py:151} WARNING - reply: b'221 exim-smtp-84f7fbf7d8-dklnz closing connection\r\n'
[2024-07-03T12:22:44.201+0000] {logging_mixin.py:151} WARNING - reply: retcode (221); Msg: b'exim-smtp-84f7fbf7d8-dklnz closing connection'
[2024-07-03T12:22:44.201+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 37, in send_emails
    robot.send_validation_results()
  File "/opt/airflow/dags/emailRobot.py", line 276, in send_validation_results
    self.send_message (address=address, subject=topic \
  File "/opt/airflow/dags/emailRobot.py", line 321, in send_message
    smtp.sendmail(from_addr= self.login, to_addrs=address \
  File "/usr/local/lib/python3.8/smtplib.py", line 906, in sendmail
    raise SMTPDataError(code, resp)
smtplib.SMTPDataError: (550, b'your mailer sends invalid headers')
[2024-07-03T12:22:44.211+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reports_workflow, task_id=id_task_send_emails, execution_date=20240702T071000, start_date=20240703T122242, end_date=20240703T122244
[2024-07-03T12:22:44.223+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1069 for task id_task_send_emails ((550, b'your mailer sends invalid headers'); 24187)
[2024-07-03T12:22:44.233+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-03T12:22:44.253+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T14:42:02.599+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_send_emails scheduled__2024-07-02T07:10:00+00:00 [queued]>
[2024-07-03T14:42:02.651+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_send_emails scheduled__2024-07-02T07:10:00+00:00 [queued]>
[2024-07-03T14:42:02.651+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-07-03T14:42:02.693+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_send_emails> on 2024-07-02 07:10:00+00:00
[2024-07-03T14:42:02.700+0000] {standard_task_runner.py:57} INFO - Started process 27942 to run task
[2024-07-03T14:42:02.718+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_send_emails', 'scheduled__2024-07-02T07:10:00+00:00', '--job-id', '1891', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpa4vzsnjh']
[2024-07-03T14:42:02.723+0000] {standard_task_runner.py:85} INFO - Job 1891: Subtask id_task_send_emails
[2024-07-03T14:42:02.830+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_send_emails scheduled__2024-07-02T07:10:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T14:42:02.961+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_send_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T07:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T07:10:00+00:00'
[2024-07-03T14:42:02.962+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T14:42:02.962+0000] {logging_mixin.py:151} INFO - #>2024-07-03 14:42:02.962760_User@StatDep: EmailRobot in screated.
[2024-07-03T14:42:02.962+0000] {logging_mixin.py:151} INFO - #>2024-07-03 14:42:02.962953_User@StatDep: send_validation_results is started...
[2024-07-03T14:42:02.974+0000] {logging_mixin.py:151} INFO -    #>2024-07-03 14:42:02.974824_conneciton to db is set.
[2024-07-03T14:42:02.976+0000] {logging_mixin.py:151} INFO -    #>2024-07-03 14:42:02.976745_cursor execution is successful.
[2024-07-03T14:42:02.977+0000] {logging_mixin.py:151} INFO -    There is no any new submissions found. The get_validation_results is over.
[2024-07-03T14:42:02.979+0000] {python.py:194} INFO - Done. Returned value was: True
[2024-07-03T14:42:03.010+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=id_task_send_emails, execution_date=20240702T071000, start_date=20240703T144202, end_date=20240703T144203
[2024-07-03T14:42:03.065+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-03T14:42:03.104+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T14:42:47.453+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_send_emails scheduled__2024-07-02T07:10:00+00:00 [queued]>
[2024-07-03T14:42:47.494+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_send_emails scheduled__2024-07-02T07:10:00+00:00 [queued]>
[2024-07-03T14:42:47.495+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-07-03T14:42:47.522+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_send_emails> on 2024-07-02 07:10:00+00:00
[2024-07-03T14:42:47.527+0000] {standard_task_runner.py:57} INFO - Started process 28006 to run task
[2024-07-03T14:42:47.546+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_send_emails', 'scheduled__2024-07-02T07:10:00+00:00', '--job-id', '1918', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpytcr2p04']
[2024-07-03T14:42:47.547+0000] {standard_task_runner.py:85} INFO - Job 1918: Subtask id_task_send_emails
[2024-07-03T14:42:47.656+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_send_emails scheduled__2024-07-02T07:10:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T14:42:47.804+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_send_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T07:10:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T07:10:00+00:00'
[2024-07-03T14:42:47.805+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T14:42:47.806+0000] {logging_mixin.py:151} INFO - #>2024-07-03 14:42:47.806830_User@StatDep: EmailRobot in screated.
[2024-07-03T14:42:47.807+0000] {logging_mixin.py:151} INFO - #>2024-07-03 14:42:47.807378_User@StatDep: send_validation_results is started...
[2024-07-03T14:42:47.820+0000] {logging_mixin.py:151} INFO -    #>2024-07-03 14:42:47.820426_conneciton to db is set.
[2024-07-03T14:42:47.822+0000] {logging_mixin.py:151} INFO -    #>2024-07-03 14:42:47.822454_cursor execution is successful.
[2024-07-03T14:42:47.822+0000] {logging_mixin.py:151} INFO -    There is no any new submissions found. The get_validation_results is over.
[2024-07-03T14:42:47.824+0000] {python.py:194} INFO - Done. Returned value was: True
[2024-07-03T14:42:47.858+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=id_task_send_emails, execution_date=20240702T071000, start_date=20240703T144247, end_date=20240703T144247
[2024-07-03T14:42:47.914+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-03T14:42:47.939+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
