[2024-07-03T09:57:01.345+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T04:50:00+00:00 [queued]>
[2024-07-03T09:57:01.355+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T04:50:00+00:00 [queued]>
[2024-07-03T09:57:01.355+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T09:57:01.367+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 04:50:00+00:00
[2024-07-03T09:57:01.374+0000] {standard_task_runner.py:57} INFO - Started process 20436 to run task
[2024-07-03T09:57:01.379+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T04:50:00+00:00', '--job-id', '301', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpy0u7hwpt']
[2024-07-03T09:57:01.381+0000] {standard_task_runner.py:85} INFO - Job 301: Subtask id_task_get_emails
[2024-07-03T09:57:01.442+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T04:50:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T09:57:01.526+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T04:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T04:50:00+00:00'
[2024-07-03T09:57:01.529+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T09:57:01.529+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 22, in get_emails
    email_conf = json.load (open(path / ("config/email_conf.json")))
NameError: name 'json' is not defined
[2024-07-03T09:57:01.539+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T045000, start_date=20240703T095701, end_date=20240703T095701
[2024-07-03T09:57:01.551+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 301 for task id_task_get_emails (name 'json' is not defined; 20436)
[2024-07-03T09:57:01.592+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-03T09:57:01.616+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T12:04:39.830+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T04:50:00+00:00 [queued]>
[2024-07-03T12:04:39.849+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T04:50:00+00:00 [queued]>
[2024-07-03T12:04:39.849+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T12:04:39.918+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 04:50:00+00:00
[2024-07-03T12:04:39.925+0000] {standard_task_runner.py:57} INFO - Started process 23260 to run task
[2024-07-03T12:04:39.935+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T04:50:00+00:00', '--job-id', '744', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmp9mk_kiei']
[2024-07-03T12:04:39.936+0000] {standard_task_runner.py:85} INFO - Job 744: Subtask id_task_get_emails
[2024-07-03T12:04:40.012+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T04:50:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T12:04:40.148+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T04:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T04:50:00+00:00'
[2024-07-03T12:04:40.149+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T12:04:40.149+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:04:40.149946_User@StatDep: EmailRobot in screated.
[2024-07-03T12:04:40.150+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:04:40.150127_User@StatDep: get_for_recent_emails is started...
[2024-07-03T12:04:40.150+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:04:40.150313_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T12:04:40.543+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T12:04:40.964+0000] {logging_mixin.py:151} INFO -    mailbox have 1 emails and the robot can process 10
[2024-07-03T12:04:41.387+0000] {logging_mixin.py:151} INFO -    #>2024-07-03 12:04:41.387424_conneciton to db is set.
[2024-07-03T12:04:41.392+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 25, in get_emails
    robot.fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 62, in fetch_emails
    return self.pop3_fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 156, in pop3_fetch_emails
    cursor.execute (query, insert_values)
psycopg2.errors.UndefinedTable: relation "sma_stat_dep.tbl_file_upload" does not exist
LINE 1: ...) AS (INSERT INTO                                 sma_stat_d...
                                                             ^

[2024-07-03T12:04:41.408+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T045000, start_date=20240703T120439, end_date=20240703T120441
[2024-07-03T12:04:41.420+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 744 for task id_task_get_emails (relation "sma_stat_dep.tbl_file_upload" does not exist
LINE 1: ...) AS (INSERT INTO                                 sma_stat_d...
                                                             ^
; 23260)
[2024-07-03T12:04:41.448+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-03T12:04:41.476+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T12:21:53.990+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T04:50:00+00:00 [queued]>
[2024-07-03T12:21:54.017+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T04:50:00+00:00 [queued]>
[2024-07-03T12:21:54.017+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T12:21:54.088+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 04:50:00+00:00
[2024-07-03T12:21:54.093+0000] {standard_task_runner.py:57} INFO - Started process 24040 to run task
[2024-07-03T12:21:54.105+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T04:50:00+00:00', '--job-id', '1004', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpp1onkn8s']
[2024-07-03T12:21:54.106+0000] {standard_task_runner.py:85} INFO - Job 1004: Subtask id_task_get_emails
[2024-07-03T12:21:54.209+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T04:50:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T12:21:54.400+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T04:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T04:50:00+00:00'
[2024-07-03T12:21:54.401+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T12:21:54.401+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:21:54.401498_User@StatDep: EmailRobot in screated.
[2024-07-03T12:21:54.401+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:21:54.401678_User@StatDep: get_for_recent_emails is started...
[2024-07-03T12:21:54.401+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:21:54.401824_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T12:21:54.816+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T12:21:55.094+0000] {logging_mixin.py:151} INFO -    mailbox have 0 emails and the robot can process 10
[2024-07-03T12:21:55.094+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:21:55.094357_User@StatDep: no emails to process, exiting pop3_fetch_emails()...
[2024-07-03T12:21:55.094+0000] {python.py:194} INFO - Done. Returned value was: True
[2024-07-03T12:21:55.135+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T045000, start_date=20240703T122153, end_date=20240703T122155
[2024-07-03T12:21:55.208+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-03T12:21:55.360+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
