[2024-07-03T09:56:51.087+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T02:55:00+00:00 [queued]>
[2024-07-03T09:56:51.097+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T02:55:00+00:00 [queued]>
[2024-07-03T09:56:51.098+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T09:56:51.117+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 02:55:00+00:00
[2024-07-03T09:56:51.125+0000] {standard_task_runner.py:57} INFO - Started process 20392 to run task
[2024-07-03T09:56:51.129+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T02:55:00+00:00', '--job-id', '278', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpedpmox81']
[2024-07-03T09:56:51.130+0000] {standard_task_runner.py:85} INFO - Job 278: Subtask id_task_get_emails
[2024-07-03T09:56:51.249+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T02:55:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T09:56:51.403+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T02:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T02:55:00+00:00'
[2024-07-03T09:56:51.404+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T09:56:51.405+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 22, in get_emails
    email_conf = json.load (open(path / ("config/email_conf.json")))
NameError: name 'json' is not defined
[2024-07-03T09:56:51.426+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T025500, start_date=20240703T095651, end_date=20240703T095651
[2024-07-03T09:56:51.446+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 278 for task id_task_get_emails (name 'json' is not defined; 20392)
[2024-07-03T09:56:51.474+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-03T09:56:51.501+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T12:04:31.740+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T02:55:00+00:00 [queued]>
[2024-07-03T12:04:31.751+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T02:55:00+00:00 [queued]>
[2024-07-03T12:04:31.752+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T12:04:31.802+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 02:55:00+00:00
[2024-07-03T12:04:31.809+0000] {standard_task_runner.py:57} INFO - Started process 23215 to run task
[2024-07-03T12:04:31.817+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T02:55:00+00:00', '--job-id', '721', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpxhlm3cl8']
[2024-07-03T12:04:31.819+0000] {standard_task_runner.py:85} INFO - Job 721: Subtask id_task_get_emails
[2024-07-03T12:04:31.881+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T02:55:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T12:04:31.969+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T02:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T02:55:00+00:00'
[2024-07-03T12:04:31.972+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T12:04:31.973+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:04:31.972971_User@StatDep: EmailRobot in screated.
[2024-07-03T12:04:31.973+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:04:31.973505_User@StatDep: get_for_recent_emails is started...
[2024-07-03T12:04:31.974+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:04:31.974029_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T12:04:32.393+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T12:04:32.980+0000] {logging_mixin.py:151} INFO -    mailbox have 1 emails and the robot can process 10
[2024-07-03T12:04:33.454+0000] {logging_mixin.py:151} INFO -    #>2024-07-03 12:04:33.454271_conneciton to db is set.
[2024-07-03T12:04:33.461+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 25, in get_emails
    robot.fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 62, in fetch_emails
    return self.pop3_fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 156, in pop3_fetch_emails
    cursor.execute (query, insert_values)
psycopg2.errors.UndefinedTable: relation "sma_stat_dep.tbl_file_upload" does not exist
LINE 1: ...) AS (INSERT INTO                                 sma_stat_d...
                                                             ^

[2024-07-03T12:04:33.488+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T025500, start_date=20240703T120431, end_date=20240703T120433
[2024-07-03T12:04:33.589+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 721 for task id_task_get_emails (relation "sma_stat_dep.tbl_file_upload" does not exist
LINE 1: ...) AS (INSERT INTO                                 sma_stat_d...
                                                             ^
; 23215)
[2024-07-03T12:04:33.605+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-03T12:04:33.637+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T12:21:26.440+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T02:55:00+00:00 [queued]>
[2024-07-03T12:21:26.467+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T02:55:00+00:00 [queued]>
[2024-07-03T12:21:26.467+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T12:21:26.489+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 02:55:00+00:00
[2024-07-03T12:21:26.494+0000] {standard_task_runner.py:57} INFO - Started process 23949 to run task
[2024-07-03T12:21:26.503+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T02:55:00+00:00', '--job-id', '964', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpetiopj44']
[2024-07-03T12:21:26.505+0000] {standard_task_runner.py:85} INFO - Job 964: Subtask id_task_get_emails
[2024-07-03T12:21:26.563+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T02:55:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T12:21:26.672+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T02:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T02:55:00+00:00'
[2024-07-03T12:21:26.673+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T12:21:26.674+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:21:26.674628_User@StatDep: EmailRobot in screated.
[2024-07-03T12:21:26.674+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:21:26.674929_User@StatDep: get_for_recent_emails is started...
[2024-07-03T12:21:26.675+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:21:26.675191_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T12:21:27.037+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T12:21:27.353+0000] {logging_mixin.py:151} INFO -    mailbox have 0 emails and the robot can process 10
[2024-07-03T12:21:27.353+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:21:27.353866_User@StatDep: no emails to process, exiting pop3_fetch_emails()...
[2024-07-03T12:21:27.354+0000] {python.py:194} INFO - Done. Returned value was: True
[2024-07-03T12:21:27.388+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T025500, start_date=20240703T122126, end_date=20240703T122127
[2024-07-03T12:21:27.433+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-03T12:21:27.461+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
