[2024-08-02T09:45:06.588+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_send_emails manual__2024-08-02T09:45:01.194071+00:00 [queued]>
[2024-08-02T09:45:06.597+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_send_emails manual__2024-08-02T09:45:01.194071+00:00 [queued]>
[2024-08-02T09:45:06.598+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-08-02T09:45:06.611+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_send_emails> on 2024-08-02 09:45:01.194071+00:00
[2024-08-02T09:45:06.617+0000] {standard_task_runner.py:57} INFO - Started process 69042 to run task
[2024-08-02T09:45:06.624+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_send_emails', 'manual__2024-08-02T09:45:01.194071+00:00', '--job-id', '1931', '--raw', '--subdir', 'DAGS_FOLDER/dag_stat_report.py', '--cfg-path', '/tmp/tmp0l1rcwcr']
[2024-08-02T09:45:06.629+0000] {standard_task_runner.py:85} INFO - Job 1931: Subtask id_task_send_emails
[2024-08-02T09:45:06.746+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_send_emails manual__2024-08-02T09:45:01.194071+00:00 [running]> on host 6bb718ab9b8f
[2024-08-02T09:45:06.918+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_send_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-08-02T09:45:01.194071+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-08-02T09:45:01.194071+00:00'
[2024-08-02T09:45:06.920+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-08-02T09:45:06.921+0000] {logging_mixin.py:151} INFO - #>2024-08-02 09:45:06.921433_User@StatDep: EmailRobot in screated.
[2024-08-02T09:45:06.921+0000] {logging_mixin.py:151} INFO - #>2024-08-02 09:45:06.921829_User@StatDep: send_validation_results is started...
[2024-08-02T09:45:06.934+0000] {logging_mixin.py:151} INFO -    #>2024-08-02 09:45:06.934619_conneciton to db is set.
[2024-08-02T09:45:06.936+0000] {logging_mixin.py:151} INFO -    #>2024-08-02 09:45:06.936372_cursor execution is successful.
[2024-08-02T09:45:06.936+0000] {logging_mixin.py:151} INFO -    There is no any new submissions found. The get_validation_results is over.
[2024-08-02T09:45:06.937+0000] {python.py:194} INFO - Done. Returned value was: True
[2024-08-02T09:45:06.959+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=id_task_send_emails, execution_date=20240802T094501, start_date=20240802T094506, end_date=20240802T094506
[2024-08-02T09:45:06.993+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-08-02T09:45:07.017+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
