[2024-07-03T12:28:01.458+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_send_emails scheduled__2024-07-02T16:55:00+00:00 [queued]>
[2024-07-03T12:28:01.466+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_send_emails scheduled__2024-07-02T16:55:00+00:00 [queued]>
[2024-07-03T12:28:01.467+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T12:28:01.478+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_send_emails> on 2024-07-02 16:55:00+00:00
[2024-07-03T12:28:01.485+0000] {standard_task_runner.py:57} INFO - Started process 24708 to run task
[2024-07-03T12:28:01.492+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_send_emails', 'scheduled__2024-07-02T16:55:00+00:00', '--job-id', '1292', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmplnzx3eoo']
[2024-07-03T12:28:01.494+0000] {standard_task_runner.py:85} INFO - Job 1292: Subtask id_task_send_emails
[2024-07-03T12:28:01.549+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_send_emails scheduled__2024-07-02T16:55:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T12:28:01.630+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_send_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T16:55:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T16:55:00+00:00'
[2024-07-03T12:28:01.631+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T12:28:01.632+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:28:01.632359_User@StatDep: EmailRobot in screated.
[2024-07-03T12:28:01.632+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:28:01.632724_User@StatDep: send_validation_results is started...
[2024-07-03T12:28:01.644+0000] {logging_mixin.py:151} INFO -    #>2024-07-03 12:28:01.644598_conneciton to db is set.
[2024-07-03T12:28:01.646+0000] {logging_mixin.py:151} INFO -    #>2024-07-03 12:28:01.646498_cursor execution is successful.
[2024-07-03T12:28:01.646+0000] {logging_mixin.py:151} INFO -    extracted information for about report sumbissions found...
[2024-07-03T12:28:15.338+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:28:15.337884_User@StatDep: email object ready to be sent:
[2024-07-03T12:28:15.751+0000] {logging_mixin.py:151} WARNING - send: 'ehlo [172.20.0.6]\r\n'
[2024-07-03T12:28:15.827+0000] {logging_mixin.py:151} WARNING - reply: b'250-smtp41.i.mail.ru\r\n'
[2024-07-03T12:28:15.828+0000] {logging_mixin.py:151} WARNING - reply: b'250-SIZE 73400320\r\n'
[2024-07-03T12:28:15.829+0000] {logging_mixin.py:151} WARNING - reply: b'250-8BITMIME\r\n'
[2024-07-03T12:28:15.829+0000] {logging_mixin.py:151} WARNING - reply: b'250-PIPELINING\r\n'
[2024-07-03T12:28:15.830+0000] {logging_mixin.py:151} WARNING - reply: b'250-DSN\r\n'
[2024-07-03T12:28:15.831+0000] {logging_mixin.py:151} WARNING - reply: b'250-SMTPUTF8\r\n'
[2024-07-03T12:28:15.832+0000] {logging_mixin.py:151} WARNING - reply: b'250 AUTH PLAIN LOGIN XOAUTH2\r\n'
[2024-07-03T12:28:15.832+0000] {logging_mixin.py:151} WARNING - reply: retcode (250); Msg: b'smtp41.i.mail.ru\nSIZE 73400320\n8BITMIME\nPIPELINING\nDSN\nSMTPUTF8\nAUTH PLAIN LOGIN XOAUTH2'
[2024-07-03T12:28:15.834+0000] {logging_mixin.py:151} WARNING - send: 'AUTH PLAIN AGtoYWxpbXpvZEBsaXN0LnJ1AEdSWFFSakMyYms0cVpIQjI2VXFk\r\n'
[2024-07-03T12:28:16.030+0000] {logging_mixin.py:151} WARNING - reply: b'235 Authentication succeeded\r\n'
[2024-07-03T12:28:16.031+0000] {logging_mixin.py:151} WARNING - reply: retcode (235); Msg: b'Authentication succeeded'
[2024-07-03T12:28:16.036+0000] {logging_mixin.py:151} WARNING - send: 'mail FROM:<khalimzod@list.ru> size=1362\r\n'
[2024-07-03T12:28:16.108+0000] {logging_mixin.py:151} WARNING - reply: b'250 OK\r\n'
[2024-07-03T12:28:16.109+0000] {logging_mixin.py:151} WARNING - reply: retcode (250); Msg: b'OK'
[2024-07-03T12:28:16.110+0000] {logging_mixin.py:151} WARNING - send: 'rcpt TO:<ihalimzod@nbt.tj>\r\n'
[2024-07-03T12:28:16.184+0000] {logging_mixin.py:151} WARNING - reply: b'250 Accepted\r\n'
[2024-07-03T12:28:16.185+0000] {logging_mixin.py:151} WARNING - reply: retcode (250); Msg: b'Accepted'
[2024-07-03T12:28:16.185+0000] {logging_mixin.py:151} WARNING - send: 'data\r\n'
[2024-07-03T12:28:16.249+0000] {logging_mixin.py:151} WARNING - reply: b'354 Enter message, ending with "." on a line by itself\r\n'
[2024-07-03T12:28:16.250+0000] {logging_mixin.py:151} WARNING - reply: retcode (354); Msg: b'Enter message, ending with "." on a line by itself'
[2024-07-03T12:28:16.251+0000] {logging_mixin.py:151} WARNING - data: (354, b'Enter message, ending with "." on a line by itself')
[2024-07-03T12:28:16.252+0000] {logging_mixin.py:151} WARNING - send: b'Content-Type: multipart/mixed; boundary="===============5222964040878505695=="\r\nMIME-Version: 1.0\r\nSubject: =?utf-8?b?b21vckBuYnQudGo6INGE0LDQudC7IEhLLnYwLjAwMDAuMzEwMTIwMjQueGxzeCDQt9Cw0LPRgNGD0LbQtdC90L3Ri9C1INCyMjAyNC0wNy0wMyAxNTozMzo1MiswMDowMCDQndCVINCf0KDQmNCd0K/Qog==?=\r\nFrom: khalimzod@list.ru\r\nTo: =?utf-8?b?0KXQsNC70LjQvNC30L7QtCDQmNGB0LzQvtC40Lsg0JDQsdC00YPRgNCw0YXQvNC+0L0gPGloYWxpbXpvZEBuYnQudGo+?=\r\n\r\n--===============5222964040878505695==\r\nContent-Type: text/plain; charset="utf-8"\r\nMIME-Version: 1.0\r\nContent-Transfer-Encoding: base64\r\n\r\n0JfQtNGA0LDQstGB0YLQstGD0LnRgtC1LCAKINCaINGB0L7QttCw0LvQtdC90LjRjiDRhNCw0LnQ\r\nuyDRgSDQuNC80LXQvdC10LwgSEsudjAuMDAwMC4zMTAxMjAyNC54bHN4LCDQt9Cw0LPRgNGD0LbQ\r\ntdC90L3Ri9C5INCyIDIwMjQtMDctMDMgMTU6MzM6NTIrMDA6MDAg0L3QtSDQsdGL0Lsg0L/RgNC4\r\n0L3Rj9GC0YHQuNGB0YLQtdC80L7QuSDQsNCy0YLQvtC80LDRgtC40YfQtdGB0LrQvtC5INC+0LHR\r\ngNCw0LHQvtGC0LrQuC4g0J/QvtC20LDQu9GD0LnRgdGC0LAsINC/0YDQvtCy0LXRgNGM0YLQtSDQ\r\nt9Cw0L/QvtC70L3QtdC90LjQtSDRhNCw0LnQu9CwLiAKINCU0L7Qv9C+0LvQvdC40YLQtdC70YzQ\r\nvdGL0LUg0YHQstC10LTQtdC90YzRjyDQv9C+INC+0LHQvdCw0YDRg9C20LXQvdC90YvQvCDQvtGI\r\n0LjQsdC60LDQvCDQv9GA0LjQu9C+0LbQtdC90L3RiyDQuiDQv9C40YHRjNC80YMuCiBDINGD0LLQ\r\nsNC20LXQvdC40LXQvCwgCiDQlNC10L/QsNGA0YLQsNC80LXQvdGCINGB0YLQsNGC0LjRgdGC0LjQ\r\nutC4INC4INC/0LvQsNGC0LXQttC90L7Qs9C+INCx0LDQu9Cw0L3RgdCwLiA=\r\n\r\n--===============5222964040878505695==--\r\n.\r\n'
[2024-07-03T12:28:16.392+0000] {logging_mixin.py:151} WARNING - reply: b'550 your mailer sends invalid headers\r\n'
[2024-07-03T12:28:16.393+0000] {logging_mixin.py:151} WARNING - reply: retcode (550); Msg: b'your mailer sends invalid headers'
[2024-07-03T12:28:16.394+0000] {logging_mixin.py:151} WARNING - data: (550, b'your mailer sends invalid headers')
[2024-07-03T12:28:16.395+0000] {logging_mixin.py:151} WARNING - send: 'rset\r\n'
[2024-07-03T12:28:16.463+0000] {logging_mixin.py:151} WARNING - reply: b'250 Reset OK\r\n'
[2024-07-03T12:28:16.464+0000] {logging_mixin.py:151} WARNING - reply: retcode (250); Msg: b'Reset OK'
[2024-07-03T12:28:16.465+0000] {logging_mixin.py:151} WARNING - send: 'QUIT\r\n'
[2024-07-03T12:28:16.734+0000] {logging_mixin.py:151} WARNING - reply: b'221 exim-smtp-84f7fbf7d8-4xvvf closing connection\r\n'
[2024-07-03T12:28:16.735+0000] {logging_mixin.py:151} WARNING - reply: retcode (221); Msg: b'exim-smtp-84f7fbf7d8-4xvvf closing connection'
[2024-07-03T12:28:16.737+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 37, in send_emails
    robot.send_validation_results()
  File "/opt/airflow/dags/emailRobot.py", line 276, in send_validation_results
    self.send_message (address=address, subject=topic \
  File "/opt/airflow/dags/emailRobot.py", line 321, in send_message
    smtp.sendmail(from_addr= self.login, to_addrs=address \
  File "/usr/local/lib/python3.8/smtplib.py", line 906, in sendmail
    raise SMTPDataError(code, resp)
smtplib.SMTPDataError: (550, b'your mailer sends invalid headers')
[2024-07-03T12:28:16.757+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reports_workflow, task_id=id_task_send_emails, execution_date=20240702T165500, start_date=20240703T122801, end_date=20240703T122816
[2024-07-03T12:28:16.781+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 1292 for task id_task_send_emails ((550, b'your mailer sends invalid headers'); 24708)
[2024-07-03T12:28:16.826+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-03T12:28:16.852+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
