[2024-07-30T11:46:53.463+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions manual__2024-07-30T11:46:51.836020+00:00 [queued]>
[2024-07-30T11:46:53.473+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions manual__2024-07-30T11:46:51.836020+00:00 [queued]>
[2024-07-30T11:46:53.473+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-07-30T11:46:53.486+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): task_validate_submissions> on 2024-07-30 11:46:51.836020+00:00
[2024-07-30T11:46:53.492+0000] {standard_task_runner.py:57} INFO - Started process 208 to run task
[2024-07-30T11:46:53.501+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'task_validate_submissions', 'manual__2024-07-30T11:46:51.836020+00:00', '--job-id', '430', '--raw', '--subdir', 'DAGS_FOLDER/dag_stat_report.py', '--cfg-path', '/tmp/tmp671h9pvg']
[2024-07-30T11:46:53.505+0000] {standard_task_runner.py:85} INFO - Job 430: Subtask task_validate_submissions
[2024-07-30T11:46:53.567+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.task_validate_submissions manual__2024-07-30T11:46:51.836020+00:00 [running]> on host 6bb718ab9b8f
[2024-07-30T11:46:53.656+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='task_validate_submissions' AIRFLOW_CTX_EXECUTION_DATE='2024-07-30T11:46:51.836020+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-07-30T11:46:51.836020+00:00'
[2024-07-30T11:46:53.657+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-30T11:46:53.669+0000] {logging_mixin.py:151} INFO - prinnnnnnnnnnnnnnnnt:  (4, 4, 1, '1HK.v0.5707.30062024.xlsx', <memory at 0x7f526bd83a00>, None, None)
[2024-07-30T11:46:53.670+0000] {logging_mixin.py:151} INFO - 2024-06-30 00:00:00
[2024-07-30T11:46:53.983+0000] {logging_mixin.py:151} INFO - <openpyxl.workbook.workbook.Workbook object at 0x7f526bc624f0>
[2024-07-30T11:46:54.863+0000] {logging_mixin.py:151} INFO - PostgreSQL connection is closed
[2024-07-30T11:46:54.864+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-07-30T11:46:54.882+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=task_validate_submissions, execution_date=20240730T114651, start_date=20240730T114653, end_date=20240730T114654
[2024-07-30T11:46:54.915+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-30T11:46:54.933+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
