[2024-07-31T12:55:01.826+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-31T12:50:00+00:00 [queued]>
[2024-07-31T12:55:01.834+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-31T12:50:00+00:00 [queued]>
[2024-07-31T12:55:01.834+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-07-31T12:55:01.846+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): task_validate_submissions> on 2024-07-31 12:50:00+00:00
[2024-07-31T12:55:01.851+0000] {standard_task_runner.py:57} INFO - Started process 25091 to run task
[2024-07-31T12:55:01.858+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'task_validate_submissions', 'scheduled__2024-07-31T12:50:00+00:00', '--job-id', '1001', '--raw', '--subdir', 'DAGS_FOLDER/dag_stat_report.py', '--cfg-path', '/tmp/tmpfwlusiei']
[2024-07-31T12:55:01.864+0000] {standard_task_runner.py:85} INFO - Job 1001: Subtask task_validate_submissions
[2024-07-31T12:55:01.946+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-31T12:50:00+00:00 [running]> on host 6bb718ab9b8f
[2024-07-31T12:55:02.069+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='task_validate_submissions' AIRFLOW_CTX_EXECUTION_DATE='2024-07-31T12:50:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-31T12:50:00+00:00'
[2024-07-31T12:55:02.071+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-31T12:55:02.087+0000] {logging_mixin.py:151} INFO - prinnnnnnnnnnnnnnnnt:  None
[2024-07-31T12:55:02.088+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-07-31T12:55:02.088+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/library/validation_reports.py", line 396, in get_hello
    select_datas(mobile_records[1])
[2024-07-31T12:55:02.088+0000] {logging_mixin.py:151} WARNING - TypeError: 'NoneType' object is not subscriptable
[2024-07-31T12:55:02.089+0000] {logging_mixin.py:151} INFO - Error while fetching data from PostgreSQL 'NoneType' object is not subscriptable None
[2024-07-31T12:55:02.089+0000] {logging_mixin.py:151} INFO - PostgreSQL connection is closed
[2024-07-31T12:55:02.089+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-07-31T12:55:02.101+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=task_validate_submissions, execution_date=20240731T125000, start_date=20240731T125501, end_date=20240731T125502
[2024-07-31T12:55:02.148+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-31T12:55:02.180+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
