[2024-07-03T09:57:24.398+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T08:20:00+00:00 [queued]>
[2024-07-03T09:57:24.407+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T08:20:00+00:00 [queued]>
[2024-07-03T09:57:24.408+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T09:57:24.421+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 08:20:00+00:00
[2024-07-03T09:57:24.429+0000] {standard_task_runner.py:57} INFO - Started process 20530 to run task
[2024-07-03T09:57:24.440+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T08:20:00+00:00', '--job-id', '345', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmp_yp0s7ih']
[2024-07-03T09:57:24.441+0000] {standard_task_runner.py:85} INFO - Job 345: Subtask id_task_get_emails
[2024-07-03T09:57:24.503+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T08:20:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T09:57:24.580+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T08:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T08:20:00+00:00'
[2024-07-03T09:57:24.581+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T09:57:24.581+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 22, in get_emails
    email_conf = json.load (open(path / ("config/email_conf.json")))
NameError: name 'json' is not defined
[2024-07-03T09:57:24.590+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T082000, start_date=20240703T095724, end_date=20240703T095724
[2024-07-03T09:57:24.602+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 345 for task id_task_get_emails (name 'json' is not defined; 20530)
[2024-07-03T09:57:24.620+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-03T09:57:24.643+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T12:04:57.756+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T08:20:00+00:00 [queued]>
[2024-07-03T12:04:57.765+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T08:20:00+00:00 [queued]>
[2024-07-03T12:04:57.766+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T12:04:57.789+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 08:20:00+00:00
[2024-07-03T12:04:57.793+0000] {standard_task_runner.py:57} INFO - Started process 23351 to run task
[2024-07-03T12:04:57.800+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T08:20:00+00:00', '--job-id', '786', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmp4d7vpkvw']
[2024-07-03T12:04:57.801+0000] {standard_task_runner.py:85} INFO - Job 786: Subtask id_task_get_emails
[2024-07-03T12:04:57.859+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T08:20:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T12:04:57.957+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T08:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T08:20:00+00:00'
[2024-07-03T12:04:57.958+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T12:04:57.960+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:04:57.960845_User@StatDep: EmailRobot in screated.
[2024-07-03T12:04:57.961+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:04:57.961057_User@StatDep: get_for_recent_emails is started...
[2024-07-03T12:04:57.961+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:04:57.961193_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T12:04:58.362+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T12:04:58.795+0000] {logging_mixin.py:151} INFO -    mailbox have 1 emails and the robot can process 10
[2024-07-03T12:04:59.264+0000] {logging_mixin.py:151} INFO -    #>2024-07-03 12:04:59.264169_conneciton to db is set.
[2024-07-03T12:04:59.274+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 25, in get_emails
    robot.fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 62, in fetch_emails
    return self.pop3_fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 156, in pop3_fetch_emails
    cursor.execute (query, insert_values)
psycopg2.errors.UndefinedTable: relation "sma_stat_dep.tbl_file_upload" does not exist
LINE 1: ...) AS (INSERT INTO                                 sma_stat_d...
                                                             ^

[2024-07-03T12:04:59.286+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T082000, start_date=20240703T120457, end_date=20240703T120459
[2024-07-03T12:04:59.301+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 786 for task id_task_get_emails (relation "sma_stat_dep.tbl_file_upload" does not exist
LINE 1: ...) AS (INSERT INTO                                 sma_stat_d...
                                                             ^
; 23351)
[2024-07-03T12:04:59.341+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-03T12:04:59.365+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T12:22:54.499+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T08:20:00+00:00 [queued]>
[2024-07-03T12:22:54.508+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T08:20:00+00:00 [queued]>
[2024-07-03T12:22:54.509+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T12:22:54.520+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 08:20:00+00:00
[2024-07-03T12:22:54.524+0000] {standard_task_runner.py:57} INFO - Started process 24210 to run task
[2024-07-03T12:22:54.530+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T08:20:00+00:00', '--job-id', '1082', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpghtd2ldi']
[2024-07-03T12:22:54.532+0000] {standard_task_runner.py:85} INFO - Job 1082: Subtask id_task_get_emails
[2024-07-03T12:22:54.582+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T08:20:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T12:22:54.660+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T08:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T08:20:00+00:00'
[2024-07-03T12:22:54.661+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T12:22:54.661+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:22:54.661643_User@StatDep: EmailRobot in screated.
[2024-07-03T12:22:54.661+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:22:54.661845_User@StatDep: get_for_recent_emails is started...
[2024-07-03T12:22:54.662+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:22:54.661991_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T12:22:55.061+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T12:22:55.394+0000] {logging_mixin.py:151} INFO -    mailbox have 0 emails and the robot can process 10
[2024-07-03T12:22:55.395+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:22:55.395296_User@StatDep: no emails to process, exiting pop3_fetch_emails()...
[2024-07-03T12:22:55.396+0000] {python.py:194} INFO - Done. Returned value was: True
[2024-07-03T12:22:55.437+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T082000, start_date=20240703T122254, end_date=20240703T122255
[2024-07-03T12:22:55.465+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-03T12:22:55.503+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-03T14:46:54.700+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T08:20:00+00:00 [queued]>
[2024-07-03T14:46:54.708+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T08:20:00+00:00 [queued]>
[2024-07-03T14:46:54.708+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-07-03T14:46:54.737+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 08:20:00+00:00
[2024-07-03T14:46:54.747+0000] {standard_task_runner.py:57} INFO - Started process 28425 to run task
[2024-07-03T14:46:54.769+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T08:20:00+00:00', '--job-id', '2096', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmp9azfuaqc']
[2024-07-03T14:46:54.773+0000] {standard_task_runner.py:85} INFO - Job 2096: Subtask id_task_get_emails
[2024-07-03T14:46:54.928+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T08:20:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T14:46:55.169+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T08:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T08:20:00+00:00'
[2024-07-03T14:46:55.170+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T14:46:55.171+0000] {logging_mixin.py:151} INFO - #>2024-07-03 14:46:55.171344_User@StatDep: EmailRobot in screated.
[2024-07-03T14:46:55.171+0000] {logging_mixin.py:151} INFO - #>2024-07-03 14:46:55.171544_User@StatDep: get_for_recent_emails is started...
[2024-07-03T14:46:55.171+0000] {logging_mixin.py:151} INFO - #>2024-07-03 14:46:55.171735_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T14:46:55.559+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T14:46:55.901+0000] {logging_mixin.py:151} INFO -    mailbox have 0 emails and the robot can process 10
[2024-07-03T14:46:55.901+0000] {logging_mixin.py:151} INFO - #>2024-07-03 14:46:55.901942_User@StatDep: no emails to process, exiting pop3_fetch_emails()...
[2024-07-03T14:46:55.902+0000] {python.py:194} INFO - Done. Returned value was: True
[2024-07-03T14:46:55.969+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T082000, start_date=20240703T144654, end_date=20240703T144655
[2024-07-03T14:46:56.043+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-03T14:46:56.149+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
