[2024-07-03T09:57:43.770+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T11:20:00+00:00 [queued]>
[2024-07-03T09:57:43.779+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T11:20:00+00:00 [queued]>
[2024-07-03T09:57:43.780+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T09:57:43.793+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 11:20:00+00:00
[2024-07-03T09:57:43.798+0000] {standard_task_runner.py:57} INFO - Started process 20602 to run task
[2024-07-03T09:57:43.806+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T11:20:00+00:00', '--job-id', '381', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmp1o1gqfsp']
[2024-07-03T09:57:43.808+0000] {standard_task_runner.py:85} INFO - Job 381: Subtask id_task_get_emails
[2024-07-03T09:57:43.870+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T11:20:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T09:57:43.976+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T11:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T11:20:00+00:00'
[2024-07-03T09:57:43.977+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T09:57:43.977+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 22, in get_emails
    email_conf = json.load (open(path / ("config/email_conf.json")))
NameError: name 'json' is not defined
[2024-07-03T09:57:43.994+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T112000, start_date=20240703T095743, end_date=20240703T095743
[2024-07-03T09:57:44.010+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 381 for task id_task_get_emails (name 'json' is not defined; 20602)
[2024-07-03T09:57:44.053+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-03T09:57:44.083+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T12:05:12.563+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T11:20:00+00:00 [queued]>
[2024-07-03T12:05:12.573+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T11:20:00+00:00 [queued]>
[2024-07-03T12:05:12.573+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T12:05:12.587+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 11:20:00+00:00
[2024-07-03T12:05:12.591+0000] {standard_task_runner.py:57} INFO - Started process 23422 to run task
[2024-07-03T12:05:12.600+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T11:20:00+00:00', '--job-id', '822', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmp_p67rtrk']
[2024-07-03T12:05:12.602+0000] {standard_task_runner.py:85} INFO - Job 822: Subtask id_task_get_emails
[2024-07-03T12:05:12.659+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T11:20:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T12:05:12.759+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T11:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T11:20:00+00:00'
[2024-07-03T12:05:12.760+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T12:05:12.760+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:05:12.760746_User@StatDep: EmailRobot in screated.
[2024-07-03T12:05:12.760+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:05:12.760940_User@StatDep: get_for_recent_emails is started...
[2024-07-03T12:05:12.761+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:05:12.761077_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T12:05:13.138+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T12:05:13.544+0000] {logging_mixin.py:151} INFO -    mailbox have 1 emails and the robot can process 10
[2024-07-03T12:05:14.205+0000] {logging_mixin.py:151} INFO -    #>2024-07-03 12:05:14.205774_conneciton to db is set.
[2024-07-03T12:05:14.212+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 25, in get_emails
    robot.fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 62, in fetch_emails
    return self.pop3_fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 156, in pop3_fetch_emails
    cursor.execute (query, insert_values)
psycopg2.errors.UndefinedTable: relation "sma_stat_dep.tbl_file_upload" does not exist
LINE 1: ...) AS (INSERT INTO                                 sma_stat_d...
                                                             ^

[2024-07-03T12:05:14.221+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T112000, start_date=20240703T120512, end_date=20240703T120514
[2024-07-03T12:05:14.234+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 822 for task id_task_get_emails (relation "sma_stat_dep.tbl_file_upload" does not exist
LINE 1: ...) AS (INSERT INTO                                 sma_stat_d...
                                                             ^
; 23422)
[2024-07-03T12:05:14.270+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-03T12:05:14.306+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T12:24:08.856+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T11:20:00+00:00 [queued]>
[2024-07-03T12:24:08.865+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T11:20:00+00:00 [queued]>
[2024-07-03T12:24:08.865+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T12:24:08.878+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 11:20:00+00:00
[2024-07-03T12:24:08.882+0000] {standard_task_runner.py:57} INFO - Started process 24372 to run task
[2024-07-03T12:24:08.886+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T11:20:00+00:00', '--job-id', '1156', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpnucyra_0']
[2024-07-03T12:24:08.887+0000] {standard_task_runner.py:85} INFO - Job 1156: Subtask id_task_get_emails
[2024-07-03T12:24:08.945+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T11:20:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T12:24:09.086+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T11:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T11:20:00+00:00'
[2024-07-03T12:24:09.088+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T12:24:09.089+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:24:09.089042_User@StatDep: EmailRobot in screated.
[2024-07-03T12:24:09.089+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:24:09.089425_User@StatDep: get_for_recent_emails is started...
[2024-07-03T12:24:09.089+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:24:09.089667_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T12:24:09.474+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T12:24:09.771+0000] {logging_mixin.py:151} INFO -    mailbox have 0 emails and the robot can process 10
[2024-07-03T12:24:09.771+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:24:09.771766_User@StatDep: no emails to process, exiting pop3_fetch_emails()...
[2024-07-03T12:24:09.772+0000] {python.py:194} INFO - Done. Returned value was: True
[2024-07-03T12:24:09.855+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T112000, start_date=20240703T122408, end_date=20240703T122409
[2024-07-03T12:24:09.905+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-03T12:24:09.981+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-03T14:47:03.731+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T11:20:00+00:00 [queued]>
[2024-07-03T14:47:03.758+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T11:20:00+00:00 [queued]>
[2024-07-03T14:47:03.759+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-07-03T14:47:03.848+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 11:20:00+00:00
[2024-07-03T14:47:03.854+0000] {standard_task_runner.py:57} INFO - Started process 28487 to run task
[2024-07-03T14:47:03.862+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T11:20:00+00:00', '--job-id', '2127', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpchq94sfm']
[2024-07-03T14:47:03.863+0000] {standard_task_runner.py:85} INFO - Job 2127: Subtask id_task_get_emails
[2024-07-03T14:47:03.972+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T11:20:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T14:47:04.133+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T11:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T11:20:00+00:00'
[2024-07-03T14:47:04.134+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T14:47:04.136+0000] {logging_mixin.py:151} INFO - #>2024-07-03 14:47:04.136325_User@StatDep: EmailRobot in screated.
[2024-07-03T14:47:04.136+0000] {logging_mixin.py:151} INFO - #>2024-07-03 14:47:04.136529_User@StatDep: get_for_recent_emails is started...
[2024-07-03T14:47:04.136+0000] {logging_mixin.py:151} INFO - #>2024-07-03 14:47:04.136681_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T14:47:04.530+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T14:47:04.874+0000] {logging_mixin.py:151} INFO -    mailbox have 0 emails and the robot can process 10
[2024-07-03T14:47:04.874+0000] {logging_mixin.py:151} INFO - #>2024-07-03 14:47:04.874457_User@StatDep: no emails to process, exiting pop3_fetch_emails()...
[2024-07-03T14:47:04.874+0000] {python.py:194} INFO - Done. Returned value was: True
[2024-07-03T14:47:04.957+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T112000, start_date=20240703T144703, end_date=20240703T144704
[2024-07-03T14:47:05.006+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-03T14:47:05.053+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
