[2024-07-03T10:35:01.377+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-03T10:30:00+00:00 [queued]>
[2024-07-03T10:35:01.388+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-03T10:30:00+00:00 [queued]>
[2024-07-03T10:35:01.388+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T10:35:01.411+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-03 10:30:00+00:00
[2024-07-03T10:35:01.416+0000] {standard_task_runner.py:57} INFO - Started process 21746 to run task
[2024-07-03T10:35:01.425+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-03T10:30:00+00:00', '--job-id', '670', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmp0di5in06']
[2024-07-03T10:35:01.427+0000] {standard_task_runner.py:85} INFO - Job 670: Subtask id_task_get_emails
[2024-07-03T10:35:01.494+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-03T10:30:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T10:35:01.609+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-03T10:30:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-03T10:30:00+00:00'
[2024-07-03T10:35:01.610+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T10:35:01.611+0000] {logging_mixin.py:151} INFO - #>2024-07-03 10:35:01.611163_User@StatDep: EmailRobot in screated.
[2024-07-03T10:35:01.611+0000] {logging_mixin.py:151} INFO - #>2024-07-03 10:35:01.611360_User@StatDep: get_for_recent_emails is started...
[2024-07-03T10:35:01.611+0000] {logging_mixin.py:151} INFO - #>2024-07-03 10:35:01.611501_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T10:35:02.076+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T10:35:02.535+0000] {logging_mixin.py:151} INFO -    mailbox have 1 emails and the robot can process 10
[2024-07-03T10:35:03.092+0000] {logging_mixin.py:151} INFO -    #>2024-07-03 10:35:03.092697_conneciton to db is set.
[2024-07-03T10:35:06.665+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 25, in get_emails
    robot.fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 62, in fetch_emails
    return self.pop3_fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 156, in pop3_fetch_emails
    cursor.execute (query, insert_values)
psycopg2.errors.NotNullViolation: null value in column "logs" of relation "tbl_files" violates not-null constraint
DETAIL:  Failing row contains (1, 1, 1, 1HK.v0.0000.31012024.xlsx, \x55457344424251414267414941414141495142676b6e712b67414541414177..., null, null).

[2024-07-03T10:35:06.682+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240703T103000, start_date=20240703T103501, end_date=20240703T103506
[2024-07-03T10:35:06.696+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 670 for task id_task_get_emails (null value in column "logs" of relation "tbl_files" violates not-null constraint
DETAIL:  Failing row contains (1, 1, 1, 1HK.v0.0000.31012024.xlsx, \x55457344424251414267414941414141495142676b6e712b67414541414177..., null, null).
; 21746)
[2024-07-03T10:35:06.740+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-03T10:35:06.777+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
