[2024-07-03T09:56:43.242+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T02:00:00+00:00 [queued]>
[2024-07-03T09:56:43.252+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T02:00:00+00:00 [queued]>
[2024-07-03T09:56:43.252+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T09:56:43.265+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 02:00:00+00:00
[2024-07-03T09:56:43.270+0000] {standard_task_runner.py:57} INFO - Started process 20360 to run task
[2024-07-03T09:56:43.278+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T02:00:00+00:00', '--job-id', '267', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpp5cmtssv']
[2024-07-03T09:56:43.280+0000] {standard_task_runner.py:85} INFO - Job 267: Subtask id_task_get_emails
[2024-07-03T09:56:43.337+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T02:00:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T09:56:43.417+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T02:00:00+00:00'
[2024-07-03T09:56:43.418+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T09:56:43.419+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 22, in get_emails
    email_conf = json.load (open(path / ("config/email_conf.json")))
NameError: name 'json' is not defined
[2024-07-03T09:56:43.428+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T020000, start_date=20240703T095643, end_date=20240703T095643
[2024-07-03T09:56:43.439+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 267 for task id_task_get_emails (name 'json' is not defined; 20360)
[2024-07-03T09:56:43.486+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-03T09:56:43.515+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T12:04:26.103+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T02:00:00+00:00 [queued]>
[2024-07-03T12:04:26.118+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T02:00:00+00:00 [queued]>
[2024-07-03T12:04:26.118+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T12:04:26.147+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 02:00:00+00:00
[2024-07-03T12:04:26.153+0000] {standard_task_runner.py:57} INFO - Started process 23193 to run task
[2024-07-03T12:04:26.170+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T02:00:00+00:00', '--job-id', '710', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpwjzhagoz']
[2024-07-03T12:04:26.171+0000] {standard_task_runner.py:85} INFO - Job 710: Subtask id_task_get_emails
[2024-07-03T12:04:26.283+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T02:00:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T12:04:26.416+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T02:00:00+00:00'
[2024-07-03T12:04:26.419+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T12:04:26.420+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:04:26.420278_User@StatDep: EmailRobot in screated.
[2024-07-03T12:04:26.420+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:04:26.420647_User@StatDep: get_for_recent_emails is started...
[2024-07-03T12:04:26.421+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:04:26.421006_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T12:04:26.805+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T12:04:27.280+0000] {logging_mixin.py:151} INFO -    mailbox have 1 emails and the robot can process 10
[2024-07-03T12:04:27.705+0000] {logging_mixin.py:151} INFO -    #>2024-07-03 12:04:27.705580_conneciton to db is set.
[2024-07-03T12:04:27.712+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 25, in get_emails
    robot.fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 62, in fetch_emails
    return self.pop3_fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 156, in pop3_fetch_emails
    cursor.execute (query, insert_values)
psycopg2.errors.UndefinedTable: relation "sma_stat_dep.tbl_file_upload" does not exist
LINE 1: ...) AS (INSERT INTO                                 sma_stat_d...
                                                             ^

[2024-07-03T12:04:27.727+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T020000, start_date=20240703T120426, end_date=20240703T120427
[2024-07-03T12:04:27.746+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 710 for task id_task_get_emails (relation "sma_stat_dep.tbl_file_upload" does not exist
LINE 1: ...) AS (INSERT INTO                                 sma_stat_d...
                                                             ^
; 23193)
[2024-07-03T12:04:27.793+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-03T12:04:27.826+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T12:20:59.970+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T02:00:00+00:00 [queued]>
[2024-07-03T12:20:59.997+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T02:00:00+00:00 [queued]>
[2024-07-03T12:20:59.998+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T12:21:00.064+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 02:00:00+00:00
[2024-07-03T12:21:00.071+0000] {standard_task_runner.py:57} INFO - Started process 23895 to run task
[2024-07-03T12:21:00.077+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T02:00:00+00:00', '--job-id', '937', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmplx3fuh3p']
[2024-07-03T12:21:00.081+0000] {standard_task_runner.py:85} INFO - Job 937: Subtask id_task_get_emails
[2024-07-03T12:21:00.141+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T02:00:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T12:21:00.222+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T02:00:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T02:00:00+00:00'
[2024-07-03T12:21:00.224+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T12:21:00.225+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:21:00.225179_User@StatDep: EmailRobot in screated.
[2024-07-03T12:21:00.225+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:21:00.225373_User@StatDep: get_for_recent_emails is started...
[2024-07-03T12:21:00.225+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:21:00.225521_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T12:21:00.623+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T12:21:00.996+0000] {logging_mixin.py:151} INFO -    mailbox have 0 emails and the robot can process 10
[2024-07-03T12:21:00.997+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:21:00.997259_User@StatDep: no emails to process, exiting pop3_fetch_emails()...
[2024-07-03T12:21:00.998+0000] {python.py:194} INFO - Done. Returned value was: True
[2024-07-03T12:21:01.065+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T020000, start_date=20240703T122059, end_date=20240703T122101
[2024-07-03T12:21:01.192+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-03T12:21:01.250+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
