[2024-07-03T09:57:31.822+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T09:20:00+00:00 [queued]>
[2024-07-03T09:57:31.831+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T09:20:00+00:00 [queued]>
[2024-07-03T09:57:31.831+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T09:57:31.844+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 09:20:00+00:00
[2024-07-03T09:57:31.848+0000] {standard_task_runner.py:57} INFO - Started process 20556 to run task
[2024-07-03T09:57:31.859+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T09:20:00+00:00', '--job-id', '357', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpt8c42s6j']
[2024-07-03T09:57:31.863+0000] {standard_task_runner.py:85} INFO - Job 357: Subtask id_task_get_emails
[2024-07-03T09:57:31.942+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T09:20:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T09:57:32.025+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T09:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T09:20:00+00:00'
[2024-07-03T09:57:32.026+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T09:57:32.027+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 22, in get_emails
    email_conf = json.load (open(path / ("config/email_conf.json")))
NameError: name 'json' is not defined
[2024-07-03T09:57:32.035+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T092000, start_date=20240703T095731, end_date=20240703T095732
[2024-07-03T09:57:32.054+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 357 for task id_task_get_emails (name 'json' is not defined; 20556)
[2024-07-03T09:57:32.069+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-03T09:57:32.086+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T12:05:03.637+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T09:20:00+00:00 [queued]>
[2024-07-03T12:05:03.647+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T09:20:00+00:00 [queued]>
[2024-07-03T12:05:03.647+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T12:05:03.686+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 09:20:00+00:00
[2024-07-03T12:05:03.694+0000] {standard_task_runner.py:57} INFO - Started process 23375 to run task
[2024-07-03T12:05:03.701+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T09:20:00+00:00', '--job-id', '798', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmp42q4au61']
[2024-07-03T12:05:03.703+0000] {standard_task_runner.py:85} INFO - Job 798: Subtask id_task_get_emails
[2024-07-03T12:05:03.793+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T09:20:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T12:05:03.905+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T09:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T09:20:00+00:00'
[2024-07-03T12:05:03.906+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T12:05:03.906+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:05:03.906894_User@StatDep: EmailRobot in screated.
[2024-07-03T12:05:03.907+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:05:03.907081_User@StatDep: get_for_recent_emails is started...
[2024-07-03T12:05:03.907+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:05:03.907211_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T12:05:04.286+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T12:05:04.741+0000] {logging_mixin.py:151} INFO -    mailbox have 1 emails and the robot can process 10
[2024-07-03T12:05:05.197+0000] {logging_mixin.py:151} INFO -    #>2024-07-03 12:05:05.197098_conneciton to db is set.
[2024-07-03T12:05:05.203+0000] {taskinstance.py:1943} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 192, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 209, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/dag_email_robot.py", line 25, in get_emails
    robot.fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 62, in fetch_emails
    return self.pop3_fetch_emails()
  File "/opt/airflow/dags/emailRobot.py", line 156, in pop3_fetch_emails
    cursor.execute (query, insert_values)
psycopg2.errors.UndefinedTable: relation "sma_stat_dep.tbl_file_upload" does not exist
LINE 1: ...) AS (INSERT INTO                                 sma_stat_d...
                                                             ^

[2024-07-03T12:05:05.217+0000] {taskinstance.py:1400} INFO - Marking task as FAILED. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T092000, start_date=20240703T120503, end_date=20240703T120505
[2024-07-03T12:05:05.345+0000] {standard_task_runner.py:104} ERROR - Failed to execute job 798 for task id_task_get_emails (relation "sma_stat_dep.tbl_file_upload" does not exist
LINE 1: ...) AS (INSERT INTO                                 sma_stat_d...
                                                             ^
; 23375)
[2024-07-03T12:05:05.365+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 1
[2024-07-03T12:05:05.405+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2024-07-03T12:23:21.620+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T09:20:00+00:00 [queued]>
[2024-07-03T12:23:21.632+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T09:20:00+00:00 [queued]>
[2024-07-03T12:23:21.632+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 1
[2024-07-03T12:23:21.645+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 09:20:00+00:00
[2024-07-03T12:23:21.649+0000] {standard_task_runner.py:57} INFO - Started process 24265 to run task
[2024-07-03T12:23:21.653+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T09:20:00+00:00', '--job-id', '1106', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpnk67w69p']
[2024-07-03T12:23:21.654+0000] {standard_task_runner.py:85} INFO - Job 1106: Subtask id_task_get_emails
[2024-07-03T12:23:21.726+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T09:20:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T12:23:21.802+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T09:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T09:20:00+00:00'
[2024-07-03T12:23:21.803+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T12:23:21.803+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:23:21.803839_User@StatDep: EmailRobot in screated.
[2024-07-03T12:23:21.804+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:23:21.804040_User@StatDep: get_for_recent_emails is started...
[2024-07-03T12:23:21.804+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:23:21.804174_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T12:23:22.157+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T12:23:22.436+0000] {logging_mixin.py:151} INFO -    mailbox have 0 emails and the robot can process 10
[2024-07-03T12:23:22.437+0000] {logging_mixin.py:151} INFO - #>2024-07-03 12:23:22.436931_User@StatDep: no emails to process, exiting pop3_fetch_emails()...
[2024-07-03T12:23:22.437+0000] {python.py:194} INFO - Done. Returned value was: True
[2024-07-03T12:23:22.473+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T092000, start_date=20240703T122321, end_date=20240703T122322
[2024-07-03T12:23:22.509+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-03T12:23:22.537+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-07-03T14:46:56.459+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T09:20:00+00:00 [queued]>
[2024-07-03T14:46:56.510+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T09:20:00+00:00 [queued]>
[2024-07-03T14:46:56.515+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-07-03T14:46:56.630+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): id_task_get_emails> on 2024-07-02 09:20:00+00:00
[2024-07-03T14:46:56.635+0000] {standard_task_runner.py:57} INFO - Started process 28442 to run task
[2024-07-03T14:46:56.678+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'id_task_get_emails', 'scheduled__2024-07-02T09:20:00+00:00', '--job-id', '2102', '--raw', '--subdir', 'DAGS_FOLDER/dag_email_robot.py', '--cfg-path', '/tmp/tmpq43fteuk']
[2024-07-03T14:46:56.679+0000] {standard_task_runner.py:85} INFO - Job 2102: Subtask id_task_get_emails
[2024-07-03T14:46:57.044+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.id_task_get_emails scheduled__2024-07-02T09:20:00+00:00 [running]> on host 6f4ef5488251
[2024-07-03T14:46:57.708+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='id_task_get_emails' AIRFLOW_CTX_EXECUTION_DATE='2024-07-02T09:20:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-02T09:20:00+00:00'
[2024-07-03T14:46:57.709+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-03T14:46:57.710+0000] {logging_mixin.py:151} INFO - #>2024-07-03 14:46:57.710441_User@StatDep: EmailRobot in screated.
[2024-07-03T14:46:57.710+0000] {logging_mixin.py:151} INFO - #>2024-07-03 14:46:57.710666_User@StatDep: get_for_recent_emails is started...
[2024-07-03T14:46:57.710+0000] {logging_mixin.py:151} INFO - #>2024-07-03 14:46:57.710805_User@StatDep: pop3_fetch_emails isstarted...
[2024-07-03T14:46:58.095+0000] {logging_mixin.py:151} INFO -    b'+OK'
[2024-07-03T14:46:58.400+0000] {logging_mixin.py:151} INFO -    mailbox have 0 emails and the robot can process 10
[2024-07-03T14:46:58.400+0000] {logging_mixin.py:151} INFO - #>2024-07-03 14:46:58.400337_User@StatDep: no emails to process, exiting pop3_fetch_emails()...
[2024-07-03T14:46:58.400+0000] {python.py:194} INFO - Done. Returned value was: True
[2024-07-03T14:46:58.467+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=id_task_get_emails, execution_date=20240702T092000, start_date=20240703T144656, end_date=20240703T144658
[2024-07-03T14:46:58.544+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-03T14:46:58.600+0000] {taskinstance.py:2784} INFO - 1 downstream tasks scheduled from follow-on schedule check
