[2024-07-29T14:45:01.859+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-29T14:40:00+00:00 [queued]>
[2024-07-29T14:45:01.868+0000] {taskinstance.py:1159} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-29T14:40:00+00:00 [queued]>
[2024-07-29T14:45:01.868+0000] {taskinstance.py:1361} INFO - Starting attempt 1 of 2
[2024-07-29T14:45:01.882+0000] {taskinstance.py:1382} INFO - Executing <Task(PythonOperator): task_validate_submissions> on 2024-07-29 14:40:00+00:00
[2024-07-29T14:45:01.889+0000] {standard_task_runner.py:57} INFO - Started process 10580 to run task
[2024-07-29T14:45:01.897+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'reports_workflow', 'task_validate_submissions', 'scheduled__2024-07-29T14:40:00+00:00', '--job-id', '380', '--raw', '--subdir', 'DAGS_FOLDER/dag_stat_report.py', '--cfg-path', '/tmp/tmp4c2v1yvn']
[2024-07-29T14:45:01.902+0000] {standard_task_runner.py:85} INFO - Job 380: Subtask task_validate_submissions
[2024-07-29T14:45:01.971+0000] {task_command.py:415} INFO - Running <TaskInstance: reports_workflow.task_validate_submissions scheduled__2024-07-29T14:40:00+00:00 [running]> on host 3fb5581aee62
[2024-07-29T14:45:02.088+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='FIRDAVS' AIRFLOW_CTX_DAG_ID='reports_workflow' AIRFLOW_CTX_TASK_ID='task_validate_submissions' AIRFLOW_CTX_EXECUTION_DATE='2024-07-29T14:40:00+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='scheduled__2024-07-29T14:40:00+00:00'
[2024-07-29T14:45:02.090+0000] {logging_mixin.py:151} INFO - path of config file:  /opt/***
[2024-07-29T14:45:02.104+0000] {logging_mixin.py:151} INFO - prinnnnnnnnnnnnnnnnt:  None
[2024-07-29T14:45:02.105+0000] {logging_mixin.py:151} WARNING - Traceback (most recent call last):
[2024-07-29T14:45:02.105+0000] {logging_mixin.py:151} WARNING -   File "/opt/***/dags/library/validation_reports.py", line 367, in get_hello
    select_datas(mobile_records[1])
[2024-07-29T14:45:02.105+0000] {logging_mixin.py:151} WARNING - TypeError: 'NoneType' object is not subscriptable
[2024-07-29T14:45:02.106+0000] {logging_mixin.py:151} INFO - Error while fetching data from PostgreSQL 'NoneType' object is not subscriptable None
[2024-07-29T14:45:02.106+0000] {logging_mixin.py:151} INFO - PostgreSQL connection is closed
[2024-07-29T14:45:02.106+0000] {python.py:194} INFO - Done. Returned value was: None
[2024-07-29T14:45:02.116+0000] {taskinstance.py:1400} INFO - Marking task as SUCCESS. dag_id=reports_workflow, task_id=task_validate_submissions, execution_date=20240729T144000, start_date=20240729T144501, end_date=20240729T144502
[2024-07-29T14:45:02.145+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2024-07-29T14:45:02.182+0000] {taskinstance.py:2784} INFO - 0 downstream tasks scheduled from follow-on schedule check
